# Generated by Django 3.0.2 on 2020-02-03 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200202_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 2, 24, 1, 552665, tzinfo=utc)),
        ),
    ]
