# Generated by Django 3.0.2 on 2020-02-04 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200203_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 4, 14, 21, 13, 699336, tzinfo=utc)),
        ),
    ]
